# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bueditor-rails 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "bueditor-rails"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Garami G\u{e1}bor"]
  s.date = "2014-11-11"
  s.description = "BUeditor for Rails"
  s.email = "hron@hron.me"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".ruby-gemset",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bueditor-rails.gemspec",
    "lib/bueditor-rails.rb",
    "lib/bueditor.rb",
    "lib/bueditor/adapter/formtastic.rb",
    "lib/bueditor/engine.rb",
    "lib/bueditor/utils.rb",
    "test/helper.rb",
    "test/test_bueditor-rails.rb",
    "vendor/assets/images/icons/README.txt",
    "vendor/assets/images/icons/bold.png",
    "vendor/assets/images/icons/code.png",
    "vendor/assets/images/icons/dot.png",
    "vendor/assets/images/icons/headers.png",
    "vendor/assets/images/icons/help.png",
    "vendor/assets/images/icons/image.png",
    "vendor/assets/images/icons/italic.png",
    "vendor/assets/images/icons/link.png",
    "vendor/assets/images/icons/ol.png",
    "vendor/assets/images/icons/preview.png",
    "vendor/assets/images/icons/quote.png",
    "vendor/assets/images/icons/separator.png",
    "vendor/assets/images/icons/strike.png",
    "vendor/assets/images/icons/teaserbr.png",
    "vendor/assets/images/icons/ul.png",
    "vendor/assets/images/icons/underline.png",
    "vendor/assets/images/icons/x1.png",
    "vendor/assets/javascripts/bueditor.js",
    "vendor/assets/javascripts/bueditor/bueditor.js",
    "vendor/assets/javascripts/bueditor/library/bue.autocomplete.js",
    "vendor/assets/javascripts/bueditor/library/bue.ctrl.js",
    "vendor/assets/javascripts/bueditor/library/bue.find.js",
    "vendor/assets/javascripts/bueditor/library/bue.history.js",
    "vendor/assets/javascripts/bueditor/library/bue.imce.js",
    "vendor/assets/javascripts/bueditor/library/bue.li.js",
    "vendor/assets/javascripts/bueditor/library/bue.markup.js",
    "vendor/assets/javascripts/bueditor/library/bue.misc.js",
    "vendor/assets/javascripts/bueditor/library/bue.popup.js",
    "vendor/assets/javascripts/bueditor/library/bue.preview.js",
    "vendor/assets/javascripts/bueditor/library/bue.tab.js",
    "vendor/assets/stylesheets/bueditor.css"
  ]
  s.homepage = "http://github.com/hron84/bueditor-rails"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.2"
  s.summary = "BUeditor for Rails"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.2.1"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.2.1"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.2.1"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

